create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports {clk_100MHZ}];
set_property  PACKAGE_PIN E3 [get_ports clk_100MHz]
set_property  IOSTANDARD LVCMOS33  [get_ports clk_100MHz]

  set_property   PACKAGE_PIN P17   [get_ports {reset}]
  set_property IOSTANDARD LVCMOS33 [get_ports {reset}]
  
  set_property   PACKAGE_PIN J15   [get_ports {sw0}]
    set_property IOSTANDARD LVCMOS33 [get_ports {sw0}]
    
set_property   PACKAGE_PIN N16   [get_ports {led_r}]
      set_property IOSTANDARD LVCMOS33 [get_ports {led_r}]
      
      set_property   PACKAGE_PIN R11   [get_ports {led_g}]
            set_property IOSTANDARD LVCMOS33 [get_ports {led_g}]
            
            set_property   PACKAGE_PIN G14   [get_ports {led_b}]
                  set_property IOSTANDARD LVCMOS33 [get_ports {led_b}]
                  

set_property   PACKAGE_PIN N17   [get_ports {start}]
      set_property IOSTANDARD LVCMOS33 [get_ports {start}]
      
      set_property   PACKAGE_PIN M17   [get_ports {enter}]
            set_property IOSTANDARD LVCMOS33 [get_ports {enter}]
      
  set_property   PACKAGE_PIN J17   [get_ports {an11[0]}]
                      set_property IOSTANDARD LVCMOS33 [get_ports {an11[0]}]
                       set_property   PACKAGE_PIN J18   [get_ports {an11[1]}]
                          set_property IOSTANDARD LVCMOS33 [get_ports {an11[1]}]
                            set_property   PACKAGE_PIN T9   [get_ports {an11[2]}]
                             set_property IOSTANDARD LVCMOS33 [get_ports {an11[2]}]
                                set_property  PACKAGE_PIN J14    [get_ports {an11[3]}]
                                   set_property IOSTANDARD LVCMOS33 [get_ports {an11[3]}]
                                          set_property  PACKAGE_PIN P14   [get_ports {an11[4]}]
                                           set_property IOSTANDARD LVCMOS33 [get_ports {an11[4]}]
                                 set_property   PACKAGE_PIN T14  [get_ports {an11[5]}]
                                  set_property IOSTANDARD LVCMOS33 [get_ports {an11[5]}]
                                  set_property   PACKAGE_PIN K2   [get_ports {an11[6]}]
                                      set_property IOSTANDARD LVCMOS33 [get_ports {an11[6]}]
                                                                   set_property   PACKAGE_PIN U13   [get_ports {an11[7]}]
                                                                        set_property IOSTANDARD LVCMOS33 [get_ports {an11[7]}]  
     set_property   PACKAGE_PIN T10    [get_ports {gg}]
set_property IOSTANDARD LVCMOS33 [get_ports {gg}]
    set_property   PACKAGE_PIN R10   [get_ports {ff}]
set_property IOSTANDARD LVCMOS33 [get_ports {ff}]
  set_property   PACKAGE_PIN K16   [get_ports {ee}]
set_property IOSTANDARD LVCMOS33 [get_ports {ee}]
  set_property   PACKAGE_PIN K13    [get_ports {dd}]
set_property IOSTANDARD LVCMOS33 [get_ports {dd}]
  set_property   PACKAGE_PIN P15   [get_ports {cc}]
set_property IOSTANDARD LVCMOS33 [get_ports {cc}]
  set_property   PACKAGE_PIN T11    [get_ports {bb}]
set_property IOSTANDARD LVCMOS33 [get_ports {bb}]
 set_property   PACKAGE_PIN L18     [get_ports {aa}]
set_property IOSTANDARD LVCMOS33 [get_ports {aa}] 